# Generated by Django 4.1 on 2022-09-04 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_ads_image_alter_category_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
    ]
